module PDDL_Compiler
  extend self

  #-----------------------------------------------
  # Predicates to PDDL
  #-----------------------------------------------

  def predicates_to_pddl(output, group = [], group_not = [], indentation = '    ')
    unless group.empty? and group_not.empty?
      group.each {|pre| output << "#{indentation}(#{pre.join(' ')})\n"}
      group_not.each {|pre| output << "#{indentation}(not (#{pre.join(' ')}))\n"}
    end
  end

  #-----------------------------------------------
  # Compile domain
  #-----------------------------------------------

  def compile_domain(domain_name, problem_name, operators, methods, predicates, state, tasks, goal_pos, goal_not)
    # Predicate declaration
    declared = {}
    negative_preconditions = false
    operators.each {|op|
      negative_preconditions = true unless op[3].empty?
      2.upto(5) {|i| op[i].each {|p| declared[p.first] = p unless declared.include?(p.first)}}
    }
    # Initial and goal states propositions must be lifted
    state.each {|p| declared[p.first] = p.join(' ?').split unless declared.include?(p.first)}
    goal_pos.each {|p| declared[p.first] = p.join(' ?').split unless declared.include?(p.first)}
    goal_not.each {|p| declared[p.first] = p.join(' ?').split unless declared.include?(p.first)}
    domain_str = "; Generated by Hype\n(define (domain #{domain_name})\n"
    domain_str << "  (:requirements :strips#{' :negative-preconditions' if negative_preconditions})\n\n  (:predicates\n"
    predicates_to_pddl(domain_str, declared.values)
    domain_str << "  )\n"
    # Operators
    operators.each {|op|
      # Header
      domain_str << "\n  (:action #{op.first}\n    :parameters (#{op[1].join(' ')})\n"
      # Preconditions
      predicates_to_pddl(domain_str << "    :precondition\n      (and\n", op[2], op[3], '        ')
      # Effects
      predicates_to_pddl(domain_str << "      )\n    :effect\n      (and\n", op[4], op[5], '        ')
      domain_str << "      )\n  )\n"
    }
    domain_str << ')'
  end

  #-----------------------------------------------
  # Compile problem
  #-----------------------------------------------

  def compile_problem(domain_name, problem_name, operators, methods, predicates, state, tasks, goal_pos, goal_not, domain_filename)
    objects = []
    start_str = ''
    state.each {|pre|
      objects.push(*pre.drop(1))
      start_str << "    (#{pre.join(' ')})\n"
    }
    tasks.drop(1).each {|pred,*terms| objects.push(*terms)}
    goal_str = ''
    goal_pos.each {|pre|
      objects.push(*pre.drop(1))
      goal_str << "      (#{pre.join(' ')})\n"
    }
    goal_not.each {|pre|
      objects.push(*pre.drop(1))
      goal_str << "      (not (#{pre.join(' ')}))\n"
    }
    objects.uniq!
    negative_preconditions = operators.all? {|op| op[3].empty?} ? '' : ' :negative-preconditions'
"; Generated by Hype
(define (problem #{problem_name})
  (:domain #{domain_name})
  (:requirements :strips#{negative_preconditions})
  (:objects\n    #{objects.join(' ')}\n  )
  (:init\n#{start_str}  )
  (:goal\n    (and\n#{goal_str}    )\n  )\n)"
  end
end