# Generated by Hype
require 'C:/Users/Mau/Desktop/HyperTensioN/Hypertension'

module Basic
  include Hypertension
  extend self

  #-----------------------------------------------
  # Domain
  #-----------------------------------------------

  @domain = {
    # Operators
    'pickup' => true,
    'drop' => true,
    # Methods
    'swap' => [
      'swap_case_0',
      'swap_case_1'
    ]
  }

  #-----------------------------------------------
  # Operators
  #-----------------------------------------------

  def pickup(a)
    apply_operator(
      # Positive preconditions
      [],
      # Negative preconditions
      [
        ['have', a]
      ],
      # Add effects
      [
        ['have', a]
      ],
      # Del effects
      []
    )
  end

  def drop(a)
    apply_operator(
      # Positive preconditions
      [
        ['have', a]
      ],
      # Negative preconditions
      [],
      # Add effects
      [],
      # Del effects
      [
        ['have', a]
      ]
    )
  end

  #-----------------------------------------------
  # Methods
  #-----------------------------------------------

  def swap_case_0(x, y)
    if applicable?(
      # Positive preconditions
      [
        ['have', x]
      ],
      # Negative preconditions
      [
        ['have', y]
      ]
    )
      yield [
        ['drop', x],
        ['pickup', y]
      ]
    end
  end

  def swap_case_1(x, y)
    if applicable?(
      # Positive preconditions
      [
        ['have', y]
      ],
      # Negative preconditions
      [
        ['have', x]
      ]
    )
      yield [
        ['drop', y],
        ['pickup', x]
      ]
    end
  end
end