# Generated by Hype
require_relative 'basic.jshop'

# Objects
[["kiwi"]] = '[["kiwi"]]'
banjo = 'banjo'
kiwi = 'kiwi'

Basic.problem(
  # Start
  {
    'have' => [
      [kiwi]
    ]
  },
  # Tasks
  [
    ['swap', banjo, kiwi]
  ],
  # Debug
  ARGV.first == 'debug'
) or abort